### ISSUE TITLE
运行时碰到该问题要怎么解决呢

### ISSUE THREAD

**Issue by aline-ss** [JunjieYang97/Meta-ControlNet#2]
之前那个问题我已经解决，这个问题需要修改配置文件哪里呢？
	
size mismatch for text_model.encoder.layers.11.layer_norm2.weight: copying a param with shape torch.Size([768]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for text_model.encoder.layers.11.layer_norm2.bias: copying a param with shape torch.Size([768]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for text_model.final_layer_norm.weight: copying a param with shape torch.Size([768]) from checkpoint, the shape in current model is torch.Size([512]).
	size mismatch for text_model.final_layer_norm.bias: copying a param with shape torch.Size([768]) from checkpoint, the shape in current model is torch.Size([512]).

**Comment by JunjieYang97** [comment]
应该是你checkpoint里的model tensor shape和你load model里的tensor shape不一样。应该是更改model batch-size 到768 或者改变你导入的checkpoint使之tensor shape与你创建的model 一样

**Comment by aline-ss** [comment]
Traceback (most recent call last):
  File "K:/hjc/SD_Control/Meta-ControlNet-master/model_train.py", line 312, in <module>
    main()
  File "K:/hjc/SD_Control/Meta-ControlNet-master/model_train.py", line 180, in main
    model = create_model('./models/cldm_v15.yaml').cpu()
  File "K:\hjc\SD_Control\Meta-ControlNet-master\cldm\model.py", line 26, in create_model

报错的地方发生在配置文件中，报错时并未到加载checkpoint那一步(更直接的我把checkpoint的路径置为空)，我按照您说的，把yaml配置文件中的768换成512，也没有起作用，能否具体到某一个文件夹的文件呢，我这边无法去按照您说的解决这个问题

**Comment by JunjieYang97** [comment]
目前来看你是使用的ControlNet的model 而不是Meta ControlNet的model，估计你的config file用的是Meta ControlNet 所以会有报错 应该需要你加入 --meta_method maml 指令 如果你打算用Meta ControlNet训练

**Comment by aline-ss** [comment]
是这行代码么
    resume_path = './models/control_sd15_ini.ckpt'
    if args.meta_method == 'maml':
        model = create_model('./models/maml_cldm_v15.yaml').cpu()
    else:
        model = create_model('./models/cldm_v15.yaml').cpu()
我按照你刚刚说的修改了，不过还是这个问题，我感觉应该是你说的，我用的是controlNet的model，想问一下你们的Meta ControlNet的model是需要重新下载么，以及checkpoint与controlnet的有区别么，这点不太清楚，原谅我刚接触这块，问的东西有点多，不好意思
